logging:
  level:
    root: info
    org:
      springframework:
        web: debug

---






amazon:
  associateId: habuma

spring:
  profiles:
    active: default
  cloud:
    config:
      enabled: true
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://tinx:admin@localhost:8761/eureka/