server:
  port: 8085
spring:
  application:
    name: zuulservice
management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://tinx:admin@localhost:8761/eureka

zuul:
  prefix: /api
  # ignored-services: '*'
  routes:
    organizationservice:
      path: /organization/**
      serviceId: organizationservice
      sensitiveHeaders:
    licensingservice: /licensing/**
    licensestatic:
      path: /licensestatic/**
      url: http://licenseservice-static:8081
    service1:
      path: /api/service1/**
      serviceId: service1
    github:
      path: /github/**
      url: https://github/com/
    auth-server:
      path: /auth/**
      url: http://localhost:8901/auth/user
      sensitiveHeaders:
  debug:
    request: true
hystrix:
  command:
    defalut:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
    organizationservice:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
