spring.jpa.database: "POSTGRESQL"
spring.datasource.platform: "postgres"
spring.datasource.show-sql: "true"
spring.datasource.driverClassName: "org.postgresql.Driver"
spring.datasource.url: "jdbc:postgresql://localhost:5432/cloud_test"
spring.datasource.username: "postgres"
spring.datasource.password: "admin"
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.hbm2ddl.auto: "update"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"